import React, { useState } from 'react';
import { BoxItem, DragonSection, DragonSetup } from '../types/level';
import { WOOL_COLORS, getWoolColor } from '../utils/colors';
import { autoGenerateDragonSections, DragonDifficulty } from '../utils/dragonSolver';
import { sounds } from '../utils/audio';
import {
  Sparkles,
  Plus,
  Trash2,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  AlertCircle,
  CheckCircle2,
  Sliders,
  Play,
  RotateCcw,
  Gauge,
  Flag,
  Layers,
  ChevronRight as CollapseIcon,
} from 'lucide-react';

interface DragonEditorProps {
  boxes: BoxItem[];
  dragon: DragonSetup;
  slotsCount: number;
  onUpdateDragon: (dragon: DragonSetup) => void;
  onStartPlaytest: () => void;
}

export const DragonEditor: React.FC<DragonEditorProps> = ({
  boxes,
  dragon,
  slotsCount,
  onUpdateDragon,
  onStartPlaytest,
}) => {
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [selectedSectionIdx, setSelectedSectionIdx] = useState<number | null>(null);
  const [difficulty, setDifficulty] = useState<DragonDifficulty>('normal');
  const [genMessage, setGenMessage] = useState<{ text: string; success: boolean } | null>(null);
  const [showSettings, setShowSettings] = useState(false);

  // Calculate wool totals
  const totalBoxWool = boxes.reduce((acc, b) => acc + b.capacity, 0);
  const totalDragonWool = dragon.sections.reduce((acc, s) => acc + s.count, 0);
  const isWoolMatched = totalBoxWool > 0 && totalBoxWool === totalDragonWool;

  // Auto Generate Dragon handler
  const handleAutoGenerate = () => {
    sounds.playPop();
    const result = autoGenerateDragonSections(boxes, slotsCount, difficulty);

    if (result.success) {
      sounds.playBoxComplete();
      onUpdateDragon({
        ...dragon,
        sections: result.sections,
      });
      setGenMessage({
        text: `Generated ${result.sections.length} sections (${result.sections.reduce((a, b) => a + b.count, 0)} wool units) with 100% solvable order!`,
        success: true,
      });
    } else {
      sounds.playBlocked();
      setGenMessage({
        text: result.message,
        success: false,
      });
    }

    setTimeout(() => setGenMessage(null), 5000);
  };

  // Add section
  const handleAddSection = () => {
    sounds.playPop();
    const newSection: DragonSection = { color: 1, count: 4 };
    onUpdateDragon({
      ...dragon,
      sections: [...dragon.sections, newSection],
    });
    setSelectedSectionIdx(dragon.sections.length);
  };

  // Update section
  const handleUpdateSection = (index: number, updates: Partial<DragonSection>) => {
    const updated = dragon.sections.map((s, idx) => (idx === index ? { ...s, ...updates } : s));
    onUpdateDragon({ ...dragon, sections: updated });
  };

  // Delete section
  const handleDeleteSection = (index: number) => {
    sounds.playPop();
    const updated = dragon.sections.filter((_, idx) => idx !== index);
    onUpdateDragon({ ...dragon, sections: updated });
    if (selectedSectionIdx === index) setSelectedSectionIdx(null);
  };

  // Move section (index 0 is Dragon Head, end is Dragon Tail)
  const handleMoveSection = (index: number, direction: 'up' | 'down') => {
    const targetIdx = direction === 'up' ? index - 1 : index + 1;
    if (targetIdx < 0 || targetIdx >= dragon.sections.length) return;
    sounds.playPop();

    const sections = [...dragon.sections];
    const temp = sections[index];
    sections[index] = sections[targetIdx];
    sections[targetIdx] = temp;

    onUpdateDragon({ ...dragon, sections });
    setSelectedSectionIdx(targetIdx);
  };

  // Collapsed Sidebar View
  if (isCollapsed) {
    return (
      <div className="w-12 bg-slate-900 border-l border-slate-800 flex flex-col items-center py-3 gap-4 flex-shrink-0 z-20 select-none">
        <button
          onClick={() => setIsCollapsed(false)}
          className="p-2 bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white rounded-lg border border-slate-700 transition"
          title="Expand Dragon Config"
        >
          <ChevronLeft className="w-4 h-4" />
        </button>

        <div className="flex-1 flex flex-col items-center justify-center gap-3">
          <span className="text-sm">🐉</span>
          <span
            className="text-xs font-semibold text-slate-400 tracking-wider font-mono rotate-90 whitespace-nowrap mt-8"
          >
            DRAGON CONFIG
          </span>
        </div>

        <div
          className={`w-3 h-3 rounded-full ${
            isWoolMatched ? 'bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.8)]' : 'bg-amber-500'
          }`}
          title={isWoolMatched ? 'Wool Matched' : 'Wool Mismatch'}
        />

        <button
          onClick={onStartPlaytest}
          className="p-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg shadow-lg hover:shadow-emerald-500/25 transition"
          title="Playtest Level"
        >
          <Play className="w-4 h-4 fill-current" />
        </button>
      </div>
    );
  }

  // Expanded Right Sidebar View
  return (
    <div className="w-88 flex-shrink-0 bg-slate-900 border-l border-slate-800 flex flex-col h-full text-slate-200 select-none shadow-2xl relative z-20">
      {/* 1. Sidebar Top Header */}
      <div className="p-3 border-b border-slate-800 bg-slate-950/70 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-base">🐉</span>
          <div>
            <h2 className="text-xs font-bold text-slate-100 tracking-wide">Dragon Configuration</h2>
            <div className="text-[10px] text-slate-400 font-mono">
              {dragon.sections.length} segments • {totalDragonWool} wool
            </div>
          </div>
        </div>

        <div className="flex items-center gap-1.5">
          <button
            onClick={() => setShowSettings(!showSettings)}
            className={`p-1.5 rounded-lg border transition ${
              showSettings
                ? 'bg-slate-800 border-cyan-500/50 text-cyan-400'
                : 'bg-slate-800/60 border-slate-700/60 text-slate-400 hover:text-slate-200'
            }`}
            title="Toggle Path & Speed Settings"
          >
            <Sliders className="w-3.5 h-3.5" />
          </button>

          <button
            onClick={() => setIsCollapsed(true)}
            className="p-1.5 bg-slate-800/60 hover:bg-slate-800 text-slate-400 hover:text-white rounded-lg border border-slate-700/60 transition"
            title="Collapse Sidebar"
          >
            <CollapseIcon className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Wool Balance Match Banner */}
      <div className="px-3 py-2 bg-slate-950/40 border-b border-slate-800/80">
        <div
          className={`flex items-center justify-between px-2.5 py-1.5 rounded-lg text-xs font-medium border ${
            isWoolMatched
              ? 'bg-emerald-950/60 border-emerald-500/40 text-emerald-400'
              : 'bg-amber-950/60 border-amber-500/40 text-amber-400'
          }`}
        >
          <div className="flex items-center gap-1.5">
            {isWoolMatched ? (
              <CheckCircle2 className="w-3.5 h-3.5 flex-shrink-0 text-emerald-400" />
            ) : (
              <AlertCircle className="w-3.5 h-3.5 flex-shrink-0 text-amber-400" />
            )}
            <span>
              Dragon: <strong className="font-mono">{totalDragonWool}</strong> / Boxes:{' '}
              <strong className="font-mono">{totalBoxWool}</strong>
            </span>
          </div>

          <span className="text-[11px] font-mono">
            {isWoolMatched
              ? '100% Match'
              : totalDragonWool > totalBoxWool
              ? `+${totalDragonWool - totalBoxWool} excess`
              : `${totalDragonWool - totalBoxWool} needed`}
          </span>
        </div>
      </div>

      {/* 2. Scrollable Middle Body */}
      <div className="flex-1 overflow-y-auto scrollbar-thin p-3 space-y-3">
        {/* Card: Auto-Generate Solvable Dragon */}
        <div className="p-3 bg-slate-950/60 border border-slate-800 rounded-xl space-y-2.5">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5 text-cyan-400" />
              <span>Auto-Generate Solvable</span>
            </span>
            <div className="flex items-center gap-0.5 bg-slate-900 border border-slate-800 rounded-md p-0.5 text-[10px]">
              {(['easy', 'normal', 'hard'] as DragonDifficulty[]).map((d) => (
                <button
                  key={d}
                  onClick={() => setDifficulty(d)}
                  className={`px-1.5 py-0.5 rounded capitalize font-medium transition ${
                    difficulty === d
                      ? 'bg-cyan-600 text-white shadow'
                      : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {d}
                </button>
              ))}
            </div>
          </div>

          <button
            onClick={handleAutoGenerate}
            className="w-full flex items-center justify-center gap-2 px-3 py-2 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white text-xs font-semibold rounded-lg shadow-md hover:shadow-cyan-500/25 transition active:scale-95"
            title="Automatically generate a 100% solvable dragon wool sequence for this level"
          >
            <Sparkles className="w-4 h-4 text-cyan-200" />
            <span>Auto Generate Dragon</span>
          </button>

          {genMessage && (
            <div
              className={`text-xs px-2.5 py-1.5 rounded-lg border flex items-center justify-between animate-fadeIn ${
                genMessage.success
                  ? 'bg-emerald-950/80 border-emerald-500/50 text-emerald-300'
                  : 'bg-rose-950/80 border-rose-500/50 text-rose-300'
              }`}
            >
              <div className="flex items-center gap-1.5">
                {genMessage.success ? (
                  <CheckCircle2 className="w-3.5 h-3.5 flex-shrink-0" />
                ) : (
                  <AlertCircle className="w-3.5 h-3.5 flex-shrink-0" />
                )}
                <span className="text-[11px] leading-tight">{genMessage.text}</span>
              </div>
              <button
                onClick={() => setGenMessage(null)}
                className="hover:opacity-75 font-bold px-1 text-slate-400"
              >
                ✕
              </button>
            </div>
          )}
        </div>

        {/* Card: Track & Speed Settings */}
        {showSettings && (
          <div className="p-3 bg-slate-950/70 border border-cyan-500/30 rounded-xl space-y-3 text-xs animate-fadeIn">
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="text-slate-300 font-medium flex items-center gap-1.5">
                  <Gauge className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Dragon Speed</span>
                </label>
                <span className="font-mono text-cyan-400 font-bold">
                  {(dragon.speed * 100).toFixed(1)} /s
                </span>
              </div>
              <input
                type="range"
                min="0.005"
                max="0.05"
                step="0.002"
                value={dragon.speed}
                onChange={(e) => onUpdateDragon({ ...dragon, speed: parseFloat(e.target.value) })}
                className="w-full accent-cyan-500 cursor-pointer"
              />
            </div>

            {/* Fog & Start Point Info */}
            <div className="p-2 bg-slate-900 border border-slate-800 rounded-lg space-y-1">
              <div className="flex items-center justify-between text-[11px]">
                <span className="text-slate-400">🌫️ Fog Zone (Locked):</span>
                <span className="font-mono text-slate-300">0% – 33.3%</span>
              </div>
              <div className="flex items-center justify-between text-[11px]">
                <span className="text-cyan-400 font-medium">🚩 Start Line Gate:</span>
                <span className="font-mono text-cyan-300 font-bold">33.3%</span>
              </div>
            </div>

            {/* Cat Checkpoints */}
            <div>
              <label className="text-slate-400 block mb-1 font-medium flex items-center gap-1.5">
                <Flag className="w-3.5 h-3.5 text-amber-400" />
                <span>Cat Checkpoints</span>
              </label>
              <div className="grid grid-cols-3 gap-1.5">
                {dragon.catPositions.map((cat, idx) => (
                  <div
                    key={cat.id}
                    className="bg-slate-900 border border-slate-800 rounded px-2 py-1 text-center"
                  >
                    <div className="text-[10px] text-slate-400 font-mono">CP {idx + 1}</div>
                    <div className="font-mono font-bold text-amber-300">
                      {Math.round(cat.progress * 100)}%
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Card: Wool Segments List (Timeline from Head to Tail) */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
              <Layers className="w-3.5 h-3.5 text-amber-400" />
              <span>Wool Timeline ({dragon.sections.length})</span>
            </span>

            <div className="flex items-center gap-1">
              <button
                onClick={handleAddSection}
                className="flex items-center gap-1 px-2 py-1 bg-slate-800 hover:bg-slate-700 text-cyan-400 hover:text-cyan-300 text-[11px] font-medium rounded border border-slate-700 transition"
                title="Add new wool section"
              >
                <Plus className="w-3 h-3" />
                <span>Add</span>
              </button>

              {dragon.sections.length > 0 && (
                <button
                  onClick={() => {
                    sounds.playPop();
                    onUpdateDragon({ ...dragon, sections: [] });
                  }}
                  className="p-1 text-slate-500 hover:text-rose-400 hover:bg-rose-950/40 rounded transition"
                  title="Clear all wool sections"
                >
                  <RotateCcw className="w-3 h-3" />
                </button>
              )}
            </div>
          </div>

          {/* Timeline segments */}
          {dragon.sections.length === 0 ? (
            <div className="p-6 text-center text-xs text-slate-500 italic bg-slate-950/40 border border-dashed border-slate-800 rounded-xl">
              No wool sections. Click "Auto Generate" or "Add" to start.
            </div>
          ) : (
            <div className="space-y-1.5">
              {dragon.sections.map((section, idx) => {
                const col = getWoolColor(section.color);
                const isSelected = selectedSectionIdx === idx;
                const isHead = idx === 0;
                const isTail = idx === dragon.sections.length - 1;

                return (
                  <div
                    key={idx}
                    className={`rounded-xl border transition-all ${
                      isSelected
                        ? 'bg-slate-950 border-cyan-500/60 shadow-lg'
                        : 'bg-slate-950/60 hover:bg-slate-950/90 border-slate-800/80 hover:border-slate-700'
                    }`}
                  >
                    {/* Main segment row */}
                    <div className="p-2 flex items-center justify-between gap-2">
                      {/* Left: Index badge & Color Pill */}
                      <div
                        onClick={() => setSelectedSectionIdx(isSelected ? null : idx)}
                        className="flex items-center gap-2 cursor-pointer flex-1 min-w-0"
                      >
                        <span
                          className={`text-[10px] font-mono px-1.5 py-0.5 rounded font-bold ${
                            isHead
                              ? 'bg-orange-950 text-orange-400 border border-orange-700/60'
                              : isTail
                              ? 'bg-slate-800 text-slate-400 border border-slate-700'
                              : 'bg-slate-900 text-slate-400 border border-slate-800'
                          }`}
                        >
                          #{idx + 1}
                          {isHead ? ' HEAD' : isTail ? ' TAIL' : ''}
                        </span>

                        <div className="flex items-center gap-1.5 truncate">
                          <span
                            className="w-4 h-4 rounded-full flex-shrink-0 shadow-sm border border-white/20"
                            style={{ backgroundColor: col.hex }}
                          />
                          <span className="text-xs font-semibold text-slate-200 truncate">
                            {col.name}
                          </span>
                        </div>
                      </div>

                      {/* Right: Quantity controls & actions */}
                      <div className="flex items-center gap-1 flex-shrink-0">
                        {/* Wool count modifier */}
                        <div className="flex items-center bg-slate-900 rounded border border-slate-800 overflow-hidden">
                          <button
                            onClick={() =>
                              handleUpdateSection(idx, {
                                count: Math.max(1, section.count - 1),
                              })
                            }
                            className="w-5 h-6 hover:bg-slate-800 text-slate-300 hover:text-white font-bold text-xs"
                          >
                            -
                          </button>
                          <input
                            type="number"
                            min="1"
                            max="50"
                            value={section.count}
                            onChange={(e) =>
                              handleUpdateSection(idx, {
                                count: Math.max(1, parseInt(e.target.value) || 1),
                              })
                            }
                            className="w-8 bg-transparent text-center font-mono text-xs font-bold text-white py-0.5"
                          />
                          <button
                            onClick={() =>
                              handleUpdateSection(idx, {
                                count: section.count + 1,
                              })
                            }
                            className="w-5 h-6 hover:bg-slate-800 text-slate-300 hover:text-white font-bold text-xs"
                          >
                            +
                          </button>
                        </div>

                        {/* Move Up / Down */}
                        <button
                          onClick={() => handleMoveSection(idx, 'up')}
                          disabled={isHead}
                          className="p-1 hover:bg-slate-800 text-slate-400 hover:text-white rounded disabled:opacity-20"
                          title="Move Closer to Head"
                        >
                          <ChevronUp className="w-3.5 h-3.5" />
                        </button>
                        <button
                          onClick={() => handleMoveSection(idx, 'down')}
                          disabled={isTail}
                          className="p-1 hover:bg-slate-800 text-slate-400 hover:text-white rounded disabled:opacity-20"
                          title="Move Towards Tail"
                        >
                          <ChevronDown className="w-3.5 h-3.5" />
                        </button>

                        {/* Delete */}
                        <button
                          onClick={() => handleDeleteSection(idx)}
                          className="p-1 text-slate-500 hover:text-rose-400 hover:bg-rose-950/40 rounded transition"
                          title="Delete Segment"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </div>

                    {/* Expanded Color Palette for active selection */}
                    {isSelected && (
                      <div className="px-2.5 pb-2.5 pt-1 border-t border-slate-800/80 bg-slate-900/50 flex items-center justify-between gap-1 animate-fadeIn">
                        <span className="text-[10px] text-slate-400 font-medium">Color:</span>
                        <div className="flex items-center gap-1.5">
                          {Object.values(WOOL_COLORS).map((c) => (
                            <button
                              key={c.id}
                              onClick={() => handleUpdateSection(idx, { color: c.id })}
                              className={`w-5 h-5 rounded-full transition-transform ${
                                section.color === c.id
                                  ? 'ring-2 ring-white scale-110 shadow-md'
                                  : 'hover:scale-105 opacity-80 hover:opacity-100'
                              }`}
                              style={{ backgroundColor: c.hex }}
                              title={c.name}
                            />
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* 3. Bottom Sticky Action Footer */}
      <div className="p-3 bg-slate-950 border-t border-slate-800 flex items-center gap-2">
        <button
          onClick={onStartPlaytest}
          className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl shadow-lg hover:shadow-emerald-500/25 transition active:scale-95"
        >
          <Play className="w-4 h-4 fill-current" />
          <span>Playtest Level</span>
        </button>
      </div>
    </div>
  );
};
