import React, { useState } from 'react';
import { BoxItem, DragonSection, DragonSetup } from '../types/level';
import { WOOL_COLORS, getWoolColor } from '../utils/colors';
import { autoGenerateDragonSections, DragonDifficulty } from '../utils/dragonSolver';
import { sounds } from '../utils/audio';
import { Sparkles, Plus, Trash2, ChevronLeft, ChevronRight, AlertCircle, CheckCircle2, Sliders, Play, RotateCcw } from 'lucide-react';

interface DragonEditorProps {
  boxes: BoxItem[];
  dragon: DragonSetup;
  slotsCount: number;
  onUpdateDragon: (dragon: DragonSetup) => void;
  onStartPlaytest: () => void;
}

export const DragonEditor: React.FC<DragonEditorProps> = ({
  boxes,
  dragon,
  slotsCount,
  onUpdateDragon,
  onStartPlaytest,
}) => {
  const [selectedSectionIdx, setSelectedSectionIdx] = useState<number | null>(null);
  const [difficulty, setDifficulty] = useState<DragonDifficulty>('normal');
  const [genMessage, setGenMessage] = useState<{ text: string; success: boolean } | null>(null);
  const [isExpanded, setIsExpanded] = useState(false);

  // Calculate totals
  const totalBoxWool = boxes.reduce((acc, b) => acc + b.capacity, 0);
  const totalDragonWool = dragon.sections.reduce((acc, s) => acc + s.count, 0);
  const isWoolMatched = totalBoxWool > 0 && totalBoxWool === totalDragonWool;

  // Auto Generate Dragon handler
  const handleAutoGenerate = () => {
    sounds.playPop();
    const result = autoGenerateDragonSections(boxes, slotsCount, difficulty);

    if (result.success) {
      sounds.playBoxComplete();
      onUpdateDragon({
        ...dragon,
        sections: result.sections,
      });
      setGenMessage({
        text: `Generated ${result.sections.length} sections (${result.sections.reduce((a, b) => a + b.count, 0)} wool units) with 100% solvable order!`,
        success: true,
      });
    } else {
      sounds.playBlocked();
      setGenMessage({
        text: result.message,
        success: false,
      });
    }

    setTimeout(() => setGenMessage(null), 5000);
  };

  // Add section
  const handleAddSection = () => {
    sounds.playPop();
    const newSection: DragonSection = { color: 1, count: 4 };
    onUpdateDragon({
      ...dragon,
      sections: [...dragon.sections, newSection],
    });
    setSelectedSectionIdx(dragon.sections.length);
  };

  // Update section
  const handleUpdateSection = (index: number, updates: Partial<DragonSection>) => {
    const updated = dragon.sections.map((s, idx) => (idx === index ? { ...s, ...updates } : s));
    onUpdateDragon({ ...dragon, sections: updated });
  };

  // Delete section
  const handleDeleteSection = (index: number) => {
    sounds.playPop();
    const updated = dragon.sections.filter((_, idx) => idx !== index);
    onUpdateDragon({ ...dragon, sections: updated });
    if (selectedSectionIdx === index) setSelectedSectionIdx(null);
  };

  // Move section
  const handleMoveSection = (index: number, direction: 'left' | 'right') => {
    const targetIdx = direction === 'left' ? index - 1 : index + 1;
    if (targetIdx < 0 || targetIdx >= dragon.sections.length) return;
    sounds.playPop();

    const sections = [...dragon.sections];
    const temp = sections[index];
    sections[index] = sections[targetIdx];
    sections[targetIdx] = temp;

    onUpdateDragon({ ...dragon, sections });
    setSelectedSectionIdx(targetIdx);
  };

  return (
    <div className="bg-slate-900 border-t border-slate-800 text-slate-200 p-3 flex flex-col gap-2.5 shadow-2xl relative z-20">
      {/* Top Bar: Controls & Summary */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        {/* Left: Section stats & match indicator */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 font-semibold text-sm">
            <span className="text-amber-400">🐉 Dragon Wool Strip</span>
            <span className="text-xs bg-slate-800 px-2 py-0.5 rounded-full font-mono text-slate-300">
              {dragon.sections.length} segments
            </span>
          </div>

          <div
            className={`flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-medium border ${
              isWoolMatched
                ? 'bg-emerald-950/70 border-emerald-500/40 text-emerald-400'
                : 'bg-amber-950/70 border-amber-500/40 text-amber-400'
            }`}
          >
            {isWoolMatched ? <CheckCircle2 className="w-3.5 h-3.5" /> : <AlertCircle className="w-3.5 h-3.5" />}
            <span>
              Dragon: <strong className="font-mono">{totalDragonWool}</strong> / Boxes: <strong className="font-mono">{totalBoxWool}</strong>
            </span>
            {!isWoolMatched && totalBoxWool > 0 && (
              <span className="text-[11px] opacity-80">
                ({totalDragonWool > totalBoxWool ? `+${totalDragonWool - totalBoxWool}` : totalDragonWool - totalBoxWool})
              </span>
            )}
          </div>
        </div>

        {/* Center / Right: Auto Generate & Playtest Buttons */}
        <div className="flex items-center gap-2">
          {/* Difficulty selector */}
          <div className="flex items-center gap-1 bg-slate-950 border border-slate-800 rounded-lg p-0.5 text-xs">
            {(['easy', 'normal', 'hard'] as DragonDifficulty[]).map((d) => (
              <button
                key={d}
                onClick={() => setDifficulty(d)}
                className={`px-2 py-1 rounded capitalize font-medium transition ${
                  difficulty === d ? 'bg-cyan-600 text-white shadow' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {d}
              </button>
            ))}
          </div>

          {/* Auto Generate Button */}
          <button
            onClick={handleAutoGenerate}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white text-xs font-semibold rounded-lg shadow-lg hover:shadow-cyan-500/25 transition active:scale-95"
            title="Automatically generate solvable dragon wool sequence from the current box layout"
          >
            <Sparkles className="w-4 h-4 text-cyan-200" />
            <span>Auto Generate Dragon</span>
          </button>

          <button
            onClick={handleAddSection}
            className="flex items-center gap-1 px-2.5 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white text-xs font-medium rounded-lg border border-slate-700 transition"
            title="Add wool section manually"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Add Section</span>
          </button>

          <button
            onClick={() => setIsExpanded(!isExpanded)}
            className={`p-1.5 rounded-lg border transition ${
              isExpanded
                ? 'bg-slate-800 border-cyan-500/50 text-cyan-400'
                : 'bg-slate-800/60 border-slate-700/60 text-slate-400 hover:text-slate-200'
            }`}
            title="Toggle Dragon Track & Speed Settings"
          >
            <Sliders className="w-4 h-4" />
          </button>

          <button
            onClick={onStartPlaytest}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold rounded-lg shadow-lg hover:shadow-emerald-500/25 transition active:scale-95"
          >
            <Play className="w-3.5 h-3.5 fill-current" />
            <span>Playtest Level</span>
          </button>
        </div>
      </div>

      {/* Generation Status Alert */}
      {genMessage && (
        <div
          className={`text-xs px-3 py-2 rounded-lg border flex items-center justify-between animate-fadeIn ${
            genMessage.success
              ? 'bg-emerald-950/80 border-emerald-500/50 text-emerald-300'
              : 'bg-rose-950/80 border-rose-500/50 text-rose-300'
          }`}
        >
          <div className="flex items-center gap-2">
            {genMessage.success ? <CheckCircle2 className="w-4 h-4" /> : <AlertCircle className="w-4 h-4" />}
            <span>{genMessage.text}</span>
          </div>
          <button onClick={() => setGenMessage(null)} className="hover:opacity-75 font-bold px-1">
            ✕
          </button>
        </div>
      )}

      {/* Expanded Track & Speed Controls */}
      {isExpanded && (
        <div className="p-3 bg-slate-950/70 border border-slate-800 rounded-xl grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
          <div>
            <label className="text-slate-400 block mb-1 font-medium">Dragon Speed (progress / sec)</label>
            <div className="flex items-center gap-3">
              <input
                type="range"
                min="0.005"
                max="0.05"
                step="0.002"
                value={dragon.speed}
                onChange={(e) => onUpdateDragon({ ...dragon, speed: parseFloat(e.target.value) })}
                className="w-full accent-cyan-500 cursor-pointer"
              />
              <span className="font-mono text-cyan-400 w-12 text-right">{(dragon.speed * 100).toFixed(1)}</span>
            </div>
          </div>

          <div>
            <label className="text-slate-400 block mb-1 font-medium">Cat Checkpoints</label>
            <div className="flex items-center gap-2">
              {dragon.catPositions.map((cat, idx) => (
                <div key={cat.id} className="flex-1 bg-slate-900 border border-slate-700/60 rounded px-2 py-1">
                  <div className="text-[10px] text-slate-400 font-mono">CP {idx + 1}</div>
                  <div className="font-mono font-semibold text-amber-300">
                    {Math.round(cat.progress * 100)}%
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="flex items-end justify-end">
            <button
              onClick={() => {
                onUpdateDragon({
                  ...dragon,
                  sections: [],
                });
              }}
              className="flex items-center gap-1 px-2.5 py-1.5 text-xs text-rose-400 hover:text-rose-300 bg-rose-950/40 hover:bg-rose-950 border border-rose-800/50 rounded-lg transition"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              <span>Clear All Sections</span>
            </button>
          </div>
        </div>
      )}

      {/* Horizontal Scrollable Dragon Wool Strip */}
      <div className="relative">
        <div className="flex items-center gap-1.5 overflow-x-auto py-2 px-1 scrollbar-thin scrollbar-thumb-slate-700 scrollbar-track-slate-900 min-h-[56px]">
          {dragon.sections.length === 0 ? (
            <div className="text-xs text-slate-500 italic py-2">
              No dragon wool sections. Click "Auto Generate Dragon" or "Add Section" to create.
            </div>
          ) : (
            dragon.sections.map((section, idx) => {
              const col = getWoolColor(section.color);
              const isSelected = selectedSectionIdx === idx;

              return (
                <div
                  key={idx}
                  onClick={() => setSelectedSectionIdx(isSelected ? null : idx)}
                  className={`group relative flex-shrink-0 flex items-center justify-center rounded-lg px-2.5 py-1.5 cursor-pointer select-none transition-all ${
                    isSelected ? 'ring-2 ring-cyan-400 scale-105 shadow-lg' : 'hover:scale-102 hover:brightness-110'
                  }`}
                  style={{
                    backgroundColor: col.hex,
                    minWidth: Math.max(36, section.count * 8),
                  }}
                  title={`Section #${idx + 1}: ${col.name} × ${section.count} wool`}
                >
                  <div className="flex items-center gap-1 text-white font-bold text-xs drop-shadow-[0_1px_2px_rgba(0,0,0,0.8)]">
                    <span>{section.count}</span>
                  </div>

                  {/* Section index badge */}
                  <span className="absolute -top-1.5 -left-1 bg-slate-950/90 text-slate-300 text-[9px] px-1 rounded font-mono border border-slate-700">
                    {idx + 1}
                  </span>
                </div>
              );
            })
          )}
        </div>
      </div>

      {/* Active Section Inspector Drawer */}
      {selectedSectionIdx !== null && selectedSectionIdx < dragon.sections.length && (
        <div className="bg-slate-950 border border-cyan-500/40 rounded-xl p-3 flex flex-wrap items-center justify-between gap-3 text-xs animate-fadeIn">
          <div className="flex items-center gap-3">
            <span className="font-semibold text-cyan-400">
              Section #{selectedSectionIdx + 1}
            </span>

            {/* Color Palette Selector */}
            <div className="flex items-center gap-1">
              {Object.values(WOOL_COLORS).map((c) => (
                <button
                  key={c.id}
                  onClick={() => handleUpdateSection(selectedSectionIdx, { color: c.id })}
                  className={`w-5 h-5 rounded-md transition-transform ${
                    dragon.sections[selectedSectionIdx].color === c.id ? 'ring-2 ring-white scale-110' : 'hover:scale-105'
                  }`}
                  style={{ backgroundColor: c.hex }}
                  title={c.name}
                />
              ))}
            </div>

            {/* Wool count modifier */}
            <div className="flex items-center gap-1.5 ml-2">
              <span className="text-slate-400">Wool units:</span>
              <button
                onClick={() =>
                  handleUpdateSection(selectedSectionIdx, {
                    count: Math.max(1, dragon.sections[selectedSectionIdx].count - 1),
                  })
                }
                className="w-5 h-5 bg-slate-800 hover:bg-slate-700 rounded text-center font-bold"
              >
                -
              </button>
              <input
                type="number"
                min="1"
                max="50"
                value={dragon.sections[selectedSectionIdx].count}
                onChange={(e) =>
                  handleUpdateSection(selectedSectionIdx, {
                    count: Math.max(1, parseInt(e.target.value) || 1),
                  })
                }
                className="w-12 bg-slate-900 border border-slate-700 text-center font-mono py-0.5 rounded text-white"
              />
              <button
                onClick={() =>
                  handleUpdateSection(selectedSectionIdx, {
                    count: dragon.sections[selectedSectionIdx].count + 1,
                  })
                }
                className="w-5 h-5 bg-slate-800 hover:bg-slate-700 rounded text-center font-bold"
              >
                +
              </button>
            </div>
          </div>

          {/* Action buttons (Reorder, Delete, Close) */}
          <div className="flex items-center gap-2">
            <button
              onClick={() => handleMoveSection(selectedSectionIdx, 'left')}
              disabled={selectedSectionIdx === 0}
              className="p-1 rounded bg-slate-800 hover:bg-slate-700 disabled:opacity-30 disabled:pointer-events-none"
              title="Move Left"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            <button
              onClick={() => handleMoveSection(selectedSectionIdx, 'right')}
              disabled={selectedSectionIdx === dragon.sections.length - 1}
              className="p-1 rounded bg-slate-800 hover:bg-slate-700 disabled:opacity-30 disabled:pointer-events-none"
              title="Move Right"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
            <button
              onClick={() => handleDeleteSection(selectedSectionIdx)}
              className="flex items-center gap-1 px-2 py-1 bg-rose-950/60 hover:bg-rose-900 text-rose-400 hover:text-white rounded border border-rose-800/60 transition"
              title="Delete Section"
            >
              <Trash2 className="w-3.5 h-3.5" />
              <span>Delete</span>
            </button>
            <button
              onClick={() => setSelectedSectionIdx(null)}
              className="px-2 py-1 text-slate-400 hover:text-white font-medium"
            >
              Done
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
