import { BoxItem, DragonSection, isBoxFrozen } from '../types/level';
import { checkExitPath } from './collision';

export interface SolverStep {
  step: number;
  boxId: number;
  boxColor: number;
  boxCapacity: number;
  unblockedBoxes: number[];
}

export interface SolveResult {
  success: boolean;
  solutionOrder: BoxItem[];
  error?: string;
  unsolvableRemaining?: BoxItem[];
}

export type DragonDifficulty = 'easy' | 'normal' | 'hard';

/**
 * Finds a valid topological extraction order of all boxes on the board.
 * Simulates clearing boxes that currently have an unobstructed exit path,
 * and accounts for launching unfrozen buses to shatter frozen (Ice) buses.
 */
export function solveBoxLayout(boxes: BoxItem[]): SolveResult {
  // Deep copy so we can simulate unfreezing without mutating original array
  const remaining = boxes.map((b) => ({ ...b }));
  const solutionOrder: BoxItem[] = [];

  const maxSteps = boxes.length * 3 + 10;
  let steps = 0;

  while (remaining.length > 0 && steps++ < maxSteps) {
    // 1. Find all unfrozen boxes that currently have a clear path
    const freeBoxes = remaining.filter(
      (b) => !isBoxFrozen(b) && !checkExitPath(b, remaining).isBlocked
    );

    if (freeBoxes.length > 0) {
      // Prioritize boxes that unblock the most other boxes
      let bestBox = freeBoxes[0];
      let maxUnblocked = -1;

      for (const candidate of freeBoxes) {
        const simulatedRemaining = remaining.filter((b) => b.id !== candidate.id);
        const newlyFreeCount = simulatedRemaining.filter(
          (b) => !isBoxFrozen(b) && !checkExitPath(b, simulatedRemaining).isBlocked
        ).length;

        if (newlyFreeCount > maxUnblocked) {
          maxUnblocked = newlyFreeCount;
          bestBox = candidate;
        }
      }

      solutionOrder.push(boxes.find((b) => b.id === bestBox.id) || bestBox);
      const idx = remaining.findIndex((b) => b.id === bestBox.id);
      remaining.splice(idx, 1);
      continue;
    }

    // 2. If no direct free boxes, check if any unfrozen box can hit an Ice box to unfreeze it!
    let unfrozenAny = false;
    for (const candidate of remaining) {
      if (isBoxFrozen(candidate)) continue;
      const hit = checkExitPath(candidate, remaining);
      if (hit.isBlocked && hit.blockingBoxId) {
        const target = remaining.find((b) => b.id === hit.blockingBoxId);
        if (target && isBoxFrozen(target)) {
          // Unfreeze target! Attacking box bounces back to its position.
          target.boxType = 'Normal';
          unfrozenAny = true;
          break; // proceed with new unfrozen box in next loop iteration
        }
      }
    }

    if (unfrozenAny) {
      continue;
    }

    // Deadlock: remaining boxes are mutually blocking each other
    return {
      success: false,
      solutionOrder,
      error: `Circular deadlock detected! ${remaining.length} boxes are stuck.`,
      unsolvableRemaining: remaining,
    };
  }

  return {
    success: remaining.length === 0,
    solutionOrder,
  };
}

/**
 * Auto-generates a sequence of dragon wool sections guaranteed to be solvable
 * with the given box layout, optional tunnel/conveyor boxes, and available slot capacity.
 */
export function autoGenerateDragonSections(
  boxes: BoxItem[],
  slotCount = 4,
  difficulty: DragonDifficulty = 'normal',
  extraBoxes: BoxItem[] = []
): { sections: DragonSection[]; success: boolean; message: string; solutionOrder: BoxItem[] } {
  const solveRes = solveBoxLayout(boxes);
  if (!solveRes.success) {
    return {
      sections: [],
      success: false,
      message: solveRes.error || 'Failed to find a clear path solution.',
      solutionOrder: [],
    };
  }

  const solutionOrder = [...solveRes.solutionOrder, ...extraBoxes];
  if (solutionOrder.length === 0) {
    return {
      sections: [],
      success: true,
      message: 'No boxes on board.',
      solutionOrder: [],
    };
  }

  // Simulation state:
  // Simulate placing boxes in slots and generating dragon wool chunks
  const rawSections: DragonSection[] = [];

  if (difficulty === 'easy') {
    // Easy: Group wool by box in order of clearance
    for (const box of solutionOrder) {
      rawSections.push({
        color: box.color,
        count: box.capacity,
      });
    }
  } else if (difficulty === 'normal') {
    // Normal: Interleave wool between the active slots
    // Simulate slot buffer of size `slotCount`
    interface SlottedBox {
      box: BoxItem;
      needed: number;
    }

    const availableQueue = [...solutionOrder];
    const activeSlots: SlottedBox[] = [];

    // Fill initial slots
    while (activeSlots.length < slotCount && availableQueue.length > 0) {
      const b = availableQueue.shift()!;
      activeSlots.push({ box: b, needed: b.capacity });
    }

    while (activeSlots.length > 0) {
      // Pick an active slot to pull wool from
      // Alternate between active slots in chunks of 2 to 4 wool units
      const targetSlot = activeSlots[0];
      const chunkSize = Math.min(
        targetSlot.needed,
        Math.floor(Math.random() * 2) + 2 // 2 or 3 wool units
      );

      rawSections.push({
        color: targetSlot.box.color,
        count: chunkSize,
      });

      targetSlot.needed -= chunkSize;

      // If this box is now full, remove it from slot and bring next available box
      if (targetSlot.needed <= 0) {
        activeSlots.shift();
        if (availableQueue.length > 0) {
          const nextBox = availableQueue.shift()!;
          activeSlots.push({ box: nextBox, needed: nextBox.capacity });
        }
      } else {
        // Rotate slots to interleave colors nicely
        if (activeSlots.length > 1) {
          const first = activeSlots.shift()!;
          activeSlots.push(first);
        }
      }
    }
  } else {
    // Hard: Higher interleaving, chunks of 1 to 2 units, tests player memory & timing
    interface SlottedBox {
      box: BoxItem;
      needed: number;
    }

    const availableQueue = [...solutionOrder];
    const activeSlots: SlottedBox[] = [];

    while (activeSlots.length < slotCount && availableQueue.length > 0) {
      const b = availableQueue.shift()!;
      activeSlots.push({ box: b, needed: b.capacity });
    }

    while (activeSlots.length > 0) {
      // Randomly pick one of the active slots to pull 1-2 wool from
      const pickIdx = Math.floor(Math.random() * activeSlots.length);
      const targetSlot = activeSlots[pickIdx];
      const chunkSize = Math.min(targetSlot.needed, Math.random() < 0.5 ? 1 : 2);

      rawSections.push({
        color: targetSlot.box.color,
        count: chunkSize,
      });

      targetSlot.needed -= chunkSize;

      if (targetSlot.needed <= 0) {
        activeSlots.splice(pickIdx, 1);
        if (availableQueue.length > 0) {
          const nextBox = availableQueue.shift()!;
          activeSlots.push({ box: nextBox, needed: nextBox.capacity });
        }
      }
    }
  }

  // Merge adjacent sections of the same color
  const mergedSections: DragonSection[] = [];
  for (const s of rawSections) {
    if (s.count <= 0) continue;
    const last = mergedSections[mergedSections.length - 1];
    if (last && last.color === s.color) {
      last.count += s.count;
    } else {
      mergedSections.push({ color: s.color, count: s.count });
    }
  }

  const totalWool = mergedSections.reduce((acc, s) => acc + s.count, 0);

  return {
    sections: mergedSections,
    success: true,
    message: `Successfully generated ${mergedSections.length} dragon sections (${totalWool} wool total) from solvable order!`,
    solutionOrder,
  };
}
