import { useState, useCallback, useEffect } from 'react';
import { CleanLevelData, BoxItem, BoxNumType, DragonSetup } from './types/level';
import { DEMO_LEVEL, STARTER_LEVEL, EMPTY_LEVEL } from './data/demoLevel';
import { autoGenerateDragonSections } from './utils/dragonSolver';
import { BOX_DIMENSIONS } from './utils/colors';
import { sounds } from './utils/audio';
import { TopNavbar } from './components/TopNavbar';
import { Sidebar } from './components/Sidebar';
import { CanvasEditor } from './components/CanvasEditor';
import { DragonEditor } from './components/DragonEditor';
import { PlaytestView } from './components/PlaytestView';
import { ImportExportModal } from './components/ImportExportModal';

function App() {
  // Initialize with DEMO_LEVEL and auto-generate initial dragon sections
  const [levelData, setLevelData] = useState<CleanLevelData>(() => {
    const demo = JSON.parse(JSON.stringify(DEMO_LEVEL)) as CleanLevelData;
    const gen = autoGenerateDragonSections(demo.boxes, demo.slots.unlockedCount || 4, 'normal');
    if (gen.success) {
      demo.dragon.sections = gen.sections;
    }
    return demo;
  });

  // Undo / Redo history for boxes
  const [history, setHistory] = useState<BoxItem[][]>([]);
  const [historyIdx, setHistoryIdx] = useState<number>(-1);

  // App UI State
  const [viewMode, setViewMode] = useState<'editor' | 'playtest'>('editor');
  const [selectedBoxIds, setSelectedBoxIds] = useState<number[]>([]);
  const [activeColor, setActiveColor] = useState<number>(1);
  const [activeNumType, setActiveNumType] = useState<BoxNumType>('Box6');
  const [gridSnap, setGridSnap] = useState<number>(0.25);
  const [showRays, setShowRays] = useState<boolean>(true);
  const [isImportExportOpen, setIsImportExportOpen] = useState<boolean>(false);

  // Push history on box change
  const updateBoxesWithHistory = useCallback((newBoxes: BoxItem[], commitToHistory = true) => {
    setLevelData((prev) => {
      if (commitToHistory) {
        setHistory((currHist) => [...currHist.slice(0, historyIdx + 1), prev.boxes]);
        setHistoryIdx((currIdx) => currIdx + 1);
      }
      return { ...prev, boxes: newBoxes };
    });
  }, [historyIdx]);

  // Undo
  const handleUndo = useCallback(() => {
    if (historyIdx >= 0 && history[historyIdx]) {
      sounds.playPop();
      const prevBoxes = history[historyIdx];
      setHistoryIdx((idx) => idx - 1);
      setLevelData((prev) => ({ ...prev, boxes: prevBoxes }));
    }
  }, [historyIdx, history]);

  // Redo
  const handleRedo = useCallback(() => {
    if (historyIdx + 1 < history.length) {
      sounds.playPop();
      const nextBoxes = history[historyIdx + 1];
      setHistoryIdx((idx) => idx + 1);
      setLevelData((prev) => ({ ...prev, boxes: nextBoxes }));
    }
  }, [historyIdx, history]);

  // Add Box tool
  const handleAddBox = (numType: BoxNumType, color: number) => {
    sounds.playPop();
    const maxId = levelData.boxes.reduce((max, b) => Math.max(max, b.id), 0);
    const capacity = BOX_DIMENSIONS[numType].capacity;

    const newBox: BoxItem = {
      id: maxId + 1,
      x: 0,
      z: -2.0,
      angle: 0,
      numType,
      capacity,
      color,
      boxType: 'Normal',
    };

    updateBoxesWithHistory([...levelData.boxes, newBox]);
    setSelectedBoxIds([newBox.id]);
  };

  // Preset loader
  const handleLoadPreset = (presetName: string) => {
    sounds.playPop();
    let selectedPreset: CleanLevelData;
    if (presetName === 'starter') {
      selectedPreset = JSON.parse(JSON.stringify(STARTER_LEVEL));
    } else if (presetName === 'empty') {
      selectedPreset = JSON.parse(JSON.stringify(EMPTY_LEVEL));
    } else {
      selectedPreset = JSON.parse(JSON.stringify(DEMO_LEVEL));
    }

    // Auto-generate dragon for the preset
    const gen = autoGenerateDragonSections(
      selectedPreset.boxes,
      selectedPreset.slots.unlockedCount || 4,
      'normal'
    );
    if (gen.success) {
      selectedPreset.dragon.sections = gen.sections;
    }

    setLevelData(selectedPreset);
    setSelectedBoxIds([]);
    setHistory([]);
    setHistoryIdx(-1);
  };

  // Dragon update
  const handleUpdateDragon = (updatedDragon: DragonSetup) => {
    setLevelData((prev) => ({ ...prev, dragon: updatedDragon }));
  };

  // Global hotkeys (Undo/Redo, Escape playtest)
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (['INPUT', 'TEXTAREA'].includes((e.target as HTMLElement).tagName)) return;

      if ((e.ctrlKey || e.metaKey) && e.key === 'z') {
        e.preventDefault();
        if (e.shiftKey) {
          handleRedo();
        } else {
          handleUndo();
        }
      } else if ((e.ctrlKey || e.metaKey) && e.key === 'y') {
        e.preventDefault();
        handleRedo();
      } else if (e.key === 'Escape' && viewMode === 'playtest') {
        setViewMode('editor');
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [handleUndo, handleRedo, viewMode]);

  return (
    <div className="w-screen h-screen flex flex-col overflow-hidden bg-slate-950 font-sans text-slate-100">
      {/* Playtest Mode Full Screen View */}
      {viewMode === 'playtest' ? (
        <PlaytestView
          levelData={levelData}
          onExit={() => setViewMode('editor')}
        />
      ) : (
        /* Level Builder Editor Mode */
        <>
          {/* Top Navbar */}
          <TopNavbar
            levelData={levelData}
            onUpdateLevelData={(updater) => setLevelData(updater)}
            onStartPlaytest={() => {
              sounds.playWhoosh();
              setViewMode('playtest');
            }}
            onOpenImportExport={() => setIsImportExportOpen(true)}
            onLoadPreset={handleLoadPreset}
          />

          {/* Main Workspace (Sidebar + Canvas + Dragon Timeline) */}
          <div className="flex-1 flex overflow-hidden">
            {/* Left Sidebar */}
            <Sidebar
              boxes={levelData.boxes}
              selectedBoxIds={selectedBoxIds}
              onSelectBoxes={setSelectedBoxIds}
              onUpdateBoxes={updateBoxesWithHistory}
              activeColor={activeColor}
              setActiveColor={setActiveColor}
              activeNumType={activeNumType}
              setActiveNumType={setActiveNumType}
              gridSnap={gridSnap}
              setGridSnap={setGridSnap}
              showRays={showRays}
              setShowRays={setShowRays}
              onAddBox={handleAddBox}
            />

            {/* Center Area: Full-height Canvas Editor */}
            <div className="flex-1 relative overflow-hidden">
              <CanvasEditor
                boxes={levelData.boxes}
                selectedBoxIds={selectedBoxIds}
                onSelectBoxes={setSelectedBoxIds}
                onUpdateBoxes={updateBoxesWithHistory}
                activeColor={activeColor}
                activeNumType={activeNumType}
                gridSnap={gridSnap}
                showRays={showRays}
                dragon={levelData.dragon}
                slots={levelData.slots}
              />
            </div>

            {/* Right Sidebar: Dragon Configuration Zone */}
            <DragonEditor
              boxes={levelData.boxes}
              dragon={levelData.dragon}
              slotsCount={levelData.slots.unlockedCount || 4}
              onUpdateDragon={handleUpdateDragon}
              onStartPlaytest={() => {
                sounds.playWhoosh();
                setViewMode('playtest');
              }}
            />
          </div>

          {/* Import/Export Modal */}
          <ImportExportModal
            isOpen={isImportExportOpen}
            onClose={() => setIsImportExportOpen(false)}
            levelData={levelData}
            onImportLevel={(imported) => {
              setLevelData(imported);
              setSelectedBoxIds([]);
              setHistory([]);
              setHistoryIdx(-1);
            }}
          />
        </>
      )}
    </div>
  );
}

export default App;
