import { useState, useCallback, useEffect } from 'react';
import { CleanLevelData, BoxItem, BoxNumType, BoxType, DragonSetup, TunnelSetup, ConveyorSetup } from './types/level';
import { DEMO_LEVEL, STARTER_LEVEL, EMPTY_LEVEL } from './data/demoLevel';
import { autoGenerateDragonSections } from './utils/dragonSolver';
import { BOX_DIMENSIONS } from './utils/colors';
import { sounds } from './utils/audio';
import { TopNavbar } from './components/TopNavbar';
import { Sidebar } from './components/Sidebar';
import { CanvasEditor } from './components/CanvasEditor';
import { DragonEditor } from './components/DragonEditor';
import { PlaytestView } from './components/PlaytestView';
import { ImportExportModal } from './components/ImportExportModal';
import { generateRandomTightLayout } from './utils/layoutGenerator';

function App() {
  // Initialize with DEMO_LEVEL and auto-generate initial dragon sections
  const [levelData, setLevelData] = useState<CleanLevelData>(() => {
    const demo = JSON.parse(JSON.stringify(DEMO_LEVEL)) as CleanLevelData;
    const tunnelBoxes = demo.tunnels?.flatMap((t) => t.queue) || [];
    const conveyorBoxes = demo.conveyors?.flatMap((c) => c.boxes) || [];
    const gen = autoGenerateDragonSections(
      demo.boxes,
      demo.slots?.unlockedCount ?? demo.slots?.count ?? 4,
      'normal',
      [...tunnelBoxes, ...conveyorBoxes]
    );
    if (gen.success) {
      demo.dragon.sections = gen.sections;
    }
    return demo;
  });

  // Undo / Redo history for boxes
  const [history, setHistory] = useState<BoxItem[][]>([]);
  const [historyIdx, setHistoryIdx] = useState<number>(-1);

  // App UI State
  const [viewMode, setViewMode] = useState<'editor' | 'playtest'>('editor');
  const [selectedBoxIds, setSelectedBoxIds] = useState<number[]>([]);
  const [selectedTunnelId, setSelectedTunnelId] = useState<number | null>(null);
  const [selectedConveyorId, setSelectedConveyorId] = useState<number | null>(null);
  const [activeColor, setActiveColor] = useState<number>(1);
  const [activeNumType, setActiveNumType] = useState<BoxNumType>('Box6');
  const [activeBoxType, setActiveBoxType] = useState<BoxType>('Normal');
  const [gridSnap, setGridSnap] = useState<number>(0.25);
  const [showRays, setShowRays] = useState<boolean>(true);
  const [isImportExportOpen, setIsImportExportOpen] = useState<boolean>(false);

  // Push history on box change
  const updateBoxesWithHistory = useCallback((newBoxes: BoxItem[], commitToHistory = true) => {
    setLevelData((prev) => {
      if (commitToHistory) {
        setHistory((currHist) => [...currHist.slice(0, historyIdx + 1), prev.boxes]);
        setHistoryIdx((currIdx) => currIdx + 1);
      }
      return { ...prev, boxes: newBoxes };
    });
  }, [historyIdx]);

  // Undo
  const handleUndo = useCallback(() => {
    if (historyIdx >= 0 && history[historyIdx]) {
      sounds.playPop();
      const prevBoxes = history[historyIdx];
      setHistoryIdx((idx) => idx - 1);
      setLevelData((prev) => ({ ...prev, boxes: prevBoxes }));
    }
  }, [historyIdx, history]);

  // Redo
  const handleRedo = useCallback(() => {
    if (historyIdx + 1 < history.length) {
      sounds.playPop();
      const nextBoxes = history[historyIdx + 1];
      setHistoryIdx((idx) => idx + 1);
      setLevelData((prev) => ({ ...prev, boxes: nextBoxes }));
    }
  }, [historyIdx, history]);

  // Add Box tool
  const handleAddBox = (numType: BoxNumType, color: number, boxType: BoxType = 'Normal') => {
    sounds.playPop();
    const maxId = levelData.boxes.reduce((max, b) => Math.max(max, b.id), 0);
    const capacity = BOX_DIMENSIONS[numType].capacity;

    const newBox: BoxItem = {
      id: maxId + 1,
      x: 0,
      z: -2.0,
      angle: 0,
      numType,
      capacity,
      color,
      boxType,
    };

    updateBoxesWithHistory([...levelData.boxes, newBox]);
    setSelectedBoxIds([newBox.id]);
    setSelectedTunnelId(null);
    setSelectedConveyorId(null);
  };

  const handleUpdateTunnels = (tunnels: TunnelSetup[]) => {
    setLevelData((prev) => ({ ...prev, tunnels }));
  };

  const handleUpdateConveyors = (conveyors: ConveyorSetup[]) => {
    setLevelData((prev) => ({ ...prev, conveyors }));
  };

  // Preset loader
  const handleLoadPreset = (presetName: string) => {
    sounds.playPop();
    let selectedPreset: CleanLevelData;
    if (presetName === 'starter') {
      selectedPreset = JSON.parse(JSON.stringify(STARTER_LEVEL));
    } else if (presetName === 'empty') {
      selectedPreset = JSON.parse(JSON.stringify(EMPTY_LEVEL));
    } else {
      selectedPreset = JSON.parse(JSON.stringify(DEMO_LEVEL));
    }

    // Auto-generate dragon for the preset
    const gen = autoGenerateDragonSections(
      selectedPreset.boxes,
      selectedPreset.slots?.unlockedCount ?? selectedPreset.slots?.count ?? 4,
      'normal'
    );
    if (gen.success) {
      selectedPreset.dragon.sections = gen.sections;
    }

    setLevelData(selectedPreset);
    setSelectedBoxIds([]);
    setHistory([]);
    setHistoryIdx(-1);
  };

  // Dragon update
  const handleUpdateDragon = (updatedDragon: DragonSetup) => {
    setLevelData((prev) => ({ ...prev, dragon: updatedDragon }));
  };

  // Clear entire board (boxes, tunnels, conveyors, dragon configuration)
  const handleClearBoard = useCallback(() => {
    if (window.confirm('Are you sure you want to clear the entire board? All boxes, tunnels, conveyors, and dragon wool sections will be removed.')) {
      sounds.playPop();
      setHistory((currHist) => [...currHist.slice(0, historyIdx + 1), levelData.boxes]);
      setHistoryIdx((currIdx) => currIdx + 1);
      setLevelData((prev) => ({
        ...prev,
        boxes: [],
        tunnels: [],
        conveyors: [],
        dragon: {
          ...prev.dragon,
          sections: [],
        },
      }));
      setSelectedBoxIds([]);
      setSelectedTunnelId(null);
      setSelectedConveyorId(null);
    }
  }, [historyIdx, levelData.boxes]);

  // Randomize 49-box tight fit layout
  const handleRandomizeLayout = useCallback(() => {
    sounds.playPop();
    const newBoxes = generateRandomTightLayout(49);

    // Save previous state to history for undo
    setHistory((currHist) => [...currHist.slice(0, historyIdx + 1), levelData.boxes]);
    setHistoryIdx((currIdx) => currIdx + 1);

    // Auto-generate dragon wool sections for the new boxes
    const slotsCount = levelData.slots?.unlockedCount ?? levelData.slots?.count ?? 4;
    const tunnelBoxes = levelData.tunnels?.flatMap((t) => t.queue) || [];
    const conveyorBoxes = levelData.conveyors?.flatMap((c) => c.boxes) || [];
    const allBoxes = [...newBoxes, ...tunnelBoxes, ...conveyorBoxes];

    const gen = autoGenerateDragonSections(newBoxes, slotsCount, 'normal', allBoxes);
    const newSections = gen.success ? gen.sections : levelData.dragon.sections;

    setLevelData((prev) => ({
      ...prev,
      boxes: newBoxes,
      dragon: {
        ...prev.dragon,
        sections: newSections,
      },
    }));
    setSelectedBoxIds([]);
    setSelectedTunnelId(null);
    setSelectedConveyorId(null);
  }, [levelData, historyIdx]);

  // Global hotkeys (Undo/Redo, Escape playtest)
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (['INPUT', 'TEXTAREA'].includes((e.target as HTMLElement).tagName)) return;

      if ((e.ctrlKey || e.metaKey) && e.key === 'z') {
        e.preventDefault();
        if (e.shiftKey) {
          handleRedo();
        } else {
          handleUndo();
        }
      } else if ((e.ctrlKey || e.metaKey) && e.key === 'y') {
        e.preventDefault();
        handleRedo();
      } else if (e.key === 'Escape' && viewMode === 'playtest') {
        setViewMode('editor');
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [handleUndo, handleRedo, viewMode]);

  return (
    <div className="w-screen h-screen flex flex-col overflow-hidden bg-slate-950 font-sans text-slate-100">
      {/* Playtest Mode Full Screen View */}
      {viewMode === 'playtest' ? (
        <PlaytestView
          levelData={levelData}
          onExit={() => setViewMode('editor')}
        />
      ) : (
        /* Level Builder Editor Mode */
        <>
          {/* Top Navbar */}
          <TopNavbar
            levelData={levelData}
            onUpdateLevelData={(updater) => setLevelData(updater)}
            onStartPlaytest={() => {
              sounds.playWhoosh();
              setViewMode('playtest');
            }}
            onOpenImportExport={() => setIsImportExportOpen(true)}
            onLoadPreset={handleLoadPreset}
            onClearBoard={handleClearBoard}
            onRandomizeLayout={handleRandomizeLayout}
            onImportLevel={(imported) => {
              setLevelData(imported);
              setSelectedBoxIds([]);
              setHistory([]);
              setHistoryIdx(-1);
            }}
          />

          {/* Main Workspace (Sidebar + Canvas + Dragon Timeline) */}
          <div className="flex-1 flex overflow-hidden">
            {/* Left Sidebar */}
            <Sidebar
              boxes={levelData.boxes}
              selectedBoxIds={selectedBoxIds}
              onSelectBoxes={(ids) => {
                setSelectedBoxIds(ids);
                if (ids.length > 0) {
                  setSelectedTunnelId(null);
                  setSelectedConveyorId(null);
                }
              }}
              onUpdateBoxes={updateBoxesWithHistory}
              activeColor={activeColor}
              setActiveColor={setActiveColor}
              activeNumType={activeNumType}
              setActiveNumType={setActiveNumType}
              activeBoxType={activeBoxType}
              setActiveBoxType={setActiveBoxType}
              gridSnap={gridSnap}
              setGridSnap={setGridSnap}
              showRays={showRays}
              setShowRays={setShowRays}
              onAddBox={handleAddBox}
              onClearBoard={handleClearBoard}
              onRandomizeLayout={handleRandomizeLayout}
              tunnels={levelData.tunnels || []}
              onUpdateTunnels={handleUpdateTunnels}
              selectedTunnelId={selectedTunnelId}
              onSelectTunnel={(id) => {
                setSelectedTunnelId(id);
                if (id !== null) {
                  setSelectedBoxIds([]);
                  setSelectedConveyorId(null);
                }
              }}
              conveyors={levelData.conveyors || []}
              onUpdateConveyors={handleUpdateConveyors}
              selectedConveyorId={selectedConveyorId}
              onSelectConveyor={(id) => {
                setSelectedConveyorId(id);
                if (id !== null) {
                  setSelectedBoxIds([]);
                  setSelectedTunnelId(null);
                }
              }}
            />

            {/* Center Area: Full-height Canvas Editor */}
            <div className="flex-1 relative overflow-hidden">
              <CanvasEditor
                boxes={levelData.boxes}
                selectedBoxIds={selectedBoxIds}
                onSelectBoxes={(ids) => {
                  setSelectedBoxIds(ids);
                  if (ids.length > 0) {
                    setSelectedTunnelId(null);
                    setSelectedConveyorId(null);
                  }
                }}
                onUpdateBoxes={updateBoxesWithHistory}
                activeColor={activeColor}
                activeNumType={activeNumType}
                gridSnap={gridSnap}
                showRays={showRays}
                dragon={levelData.dragon}
                slots={levelData.slots}
                tunnels={levelData.tunnels || []}
                onUpdateTunnels={handleUpdateTunnels}
                selectedTunnelId={selectedTunnelId}
                onSelectTunnel={(id) => {
                  setSelectedTunnelId(id);
                  if (id !== null) {
                    setSelectedBoxIds([]);
                    setSelectedConveyorId(null);
                  }
                }}
                conveyors={levelData.conveyors || []}
                onUpdateConveyors={handleUpdateConveyors}
                selectedConveyorId={selectedConveyorId}
                onSelectConveyor={(id) => {
                  setSelectedConveyorId(id);
                  if (id !== null) {
                    setSelectedBoxIds([]);
                    setSelectedTunnelId(null);
                  }
                }}
              />
            </div>

            {/* Right Sidebar: Dragon Configuration Zone */}
            <DragonEditor
              boxes={levelData.boxes}
              dragon={levelData.dragon}
              slotsCount={levelData.slots?.unlockedCount ?? levelData.slots?.count ?? 4}
              tunnels={levelData.tunnels || []}
              conveyors={levelData.conveyors || []}
              onUpdateDragon={handleUpdateDragon}
              onStartPlaytest={() => {
                sounds.playWhoosh();
                setViewMode('playtest');
              }}
            />
          </div>

          {/* Import/Export Modal */}
          <ImportExportModal
            isOpen={isImportExportOpen}
            onClose={() => setIsImportExportOpen(false)}
            levelData={levelData}
            onImportLevel={(imported) => {
              setLevelData(imported);
              setSelectedBoxIds([]);
              setHistory([]);
              setHistoryIdx(-1);
            }}
          />
        </>
      )}
    </div>
  );
}

export default App;
